### ISSUE TITLE
Stop servers using script

### ISSUE THREAD

**Issue by Savidude** [wso2/puppet-micro-integrator#6]
**Description:**
Servers get stopped by obtaining the PID and then killing the process. Kill servers using the `stop` command on the shell script instead.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
@Savidude 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
​​This is currently not part of our plans or a priority, so we are closing the issue for now. We will reopen it if we decide to pursue this in the future.
